POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Amedamawe",
    "author": "calmedsaaggg",
    "url": "awawaaw",
    "likes": 2201
}

###
GET http://localhost:3003/api/blogs/

###
DELETE http://localhost:3003/api/blogs/63d176c54a9732e2efd13e27

###
PUT http://localhost:3003/api/blogs/63d176c54a9732e2efd13e27
Content-Type: application/json

{
    "likes": 7654778
}