POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "ebbnflow",
    "author": "calmedsaaggg",
    "url": "awawaaw",
    "userId": "63d287a3aae1c84eab57bda1" 
}

###
GET http://localhost:3003/api/blogs/

###
DELETE http://localhost:3003/api/blogs/63d178034e9b050b70b377e8

###
PUT http://localhost:3003/api/blogs/63d0061ad11cdcb89d0171f1
Content-Type: application/json

{
    "likes": 7999
}